### ISSUE TITLE
Some tests still missing from exam_test.py

### ISSUE THREAD

**Issue by KladeRe** [rela-v/py-study-planner#12]
---
name: Feature request
about: Suggest an idea for this project
title: ''Some tests still missing from exam_test.py"
labels: ''enhancement"
assignees: ''KladeRe"

---

**Is your feature request related to a problem? Please describe.**
Some tests are still missing for the exam.py file. 

**Describe the solution you'd like**
I will try to implement tests for the rest of the functions in the file.

**Additional context**
There will be some functions which will be hard to test, mainly those which require a lot of user input such as add_exam(). I can modify the functions so that one function takes care of grabbing the user input and a second function handles the data from the first function. The second function would then be tested. But what do you think of this approach?

**Comment by rela-v** [comment]
Sorry about the late reply - good points you raised for sure! Something I've been thinking about is changing the structure of the code to utilize OOP. That would make it far more standardized and easier to test (and would make it easier to follow the DRY convention). It would also make this issue specifically much easier to deal with. Probably some things that should be classes are "exams" and "schedules". Since we're making progress with the tests right now and I don't want to waste your great effort, I think what I'm going to do is hold off on this issue/PR pair review process until the code has been refactored. We can leave this issue open if you want, or alternatively if you would like you can feel free to close and create another issue when the refactoring is done. I am going to post an issue/PR pair for this and assign myself, if I leave off somewhere in the middle feel free to pick up where I left off (or not, totally up to you). Does this sound okay to you?

- Rela

**Comment by KladeRe** [comment]
Sounds good to me.
