### ISSUE TITLE
[Python] The library unittest could be used for writing tests

### ISSUE THREAD

**Issue by KladeRe** [rela-v/py-study-planner#8]
**Is your feature request related to a problem? Please describe.**
Currently the tests are written as functions.

**Describe the solution you'd like**
Tests could be written using Pythons unittest library

**Describe alternatives you've considered**
If unittest shouldn't be used in this project the tests can also be written as functions.

**Comment by rela-v** [comment]
> **Is your feature request related to a problem? Please describe.** Currently the tests are written as functions.
> Currently the tests are written as functions.
> **Describe the solution you'd like** Tests could be written using Pythons unittest library
> Tests could be written using Pythons unittest library
> **Describe alternatives you've considered** If unittest shouldn't be used in this project the tests can also be written as functions.
> If unittest shouldn't be used in this project the tests can also be written as functions.

It's not necessarily that unittest shouldn't be used in this project, the built-in unittest module is actually quite good and I used it for some time. If you prefer unittest and you think that it is better, then it's a fine solution, it's just that the project is currently using pytest (please refer to https://github.com/rela-v/py-study-planner/pull/7 for the relevant PR message).

There are a few online resources regarding the benefits of using pytest over unittest. Just so you know (which is also noted in https://github.com/rela-v/py-study-planner/pull/7), the project also uses coverage, so you may want to use the currently working following command:

`coverage -m run pytest tests/`

I'll keep this issue open for now, since I actually only made the switch to pytest last week, so if you do feel strongly about using unittest feel free to respond below. If you agree with using pytest, just let me know below as well and I'll close the issue. In the spirit of open source, I'll leave this one up to you.

Since this is your third excellent contribution, I will go ahead and invite you as a collaborator!: just be sure to follow the new CONTRIBUTING.md guidelines (1) file an issue first, 2) feel free to fork and then code [or not] while you wait for issue assignment, and *once assigned*, then 3) post PR with the appropriate template found in the .github/ folder of the project). This is for your benefit so that you don't sink too much time into issues that are covered by other PR's, etc.

Thank you so much again for your invaluable contributions. I am excited to see what comes next!

- Rela

**Comment by KladeRe** [comment]
I have used pytest a bit before and I do think I will be able to write tests for this project using it. You can close the issue!
